// Banco de dados de motos e volumes de óleo de suspensão
const motorcycleDatabase = [
  {
    model: "honda cb 300",
    leftVolume: "323 ml",
    rightVolume: "323 ml",
    fluidLevel: "128 ml",
    recommendation: "Utilize óleo de suspensão SAE 10W para melhor desempenho.",
  },
  {
    model: "honda cg 160",
    leftVolume: "150 ml",
    rightVolume: "250 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W para este modelo.",
  },
  {
    model: "honda falcon 400",
    leftVolume: "529 ± 2,5 ml",
    rightVolume: "529 ± 2,5 ml",
    recommendation: "Utilize óleo de suspensão SAE 10W para melhor desempenho.",
  },
  {
    model: "honda xre 190",
    leftVolume: "176 ± 2,5 ml",
    rightVolume: "176 ± 2,5 ml",
    recommendation: "Para suspensões mais macias, pode-se usar óleo SAE 10W.",
  },
  {
    model: "honda crf 230",
    leftVolume: "380 ± 2,5 ml",
    rightVolume: "380 ± 2,5 ml",
    recommendation:
      "Óleo de suspensão SAE 10W é o mais indicado para este modelo.",
  },
  {
    model: "honda xre 300",
    leftVolume: "547 ± 2,5 ml",
    rightVolume: "547 ± 2,5 ml",
    recommendation:
      "Óleo de suspensão SAE 10W é o mais indicado para este modelo.",
  },
  {
    model: "honda pcx 150",
    leftVolume: "116 ± 2,5 ml",
    rightVolume: "116 ± 2,5 ml",
    recommendation:
      "Óleo de suspensão SAE 10W é o mais indicado para este modelo.",
  },
  {
    model: "honda cb twister 250",
    leftVolume: "306 ± 2,5 ml",
    rightVolume: "306 ± 2,5 ml",
    recommendation:
      "Para melhor desempenho em estradas irregulares, use óleo SAE 10W.",
  },
  {
    model: "honda biz 125",
    leftVolume: "60 ml",
    rightVolume: "60 ml",
    recommendation: "Use óleo de suspensão SAE 10W neste modelo.",
  },
  {
    model: "honda crf 250",
    leftVolume: "637 ± 2,5 ml",
    rightVolume: "637 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda pop 110",
    leftVolume: "58 ± 1 ml",
    rightVolume: "58 ± 1 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda cg 160 2016",
    leftVolume: "139 ± 2,5 ml",
    rightVolume: "139 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda cg 160 2025",
    leftVolume: "182 ± 2,5 ml",
    rightVolume: "198 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda bros 150 e 160",
    leftVolume: "180 ± 2,5 ml",
    rightVolume: "180 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda bros 125 2013",
    leftVolume: "176 ± 2,5 ml",
    rightVolume: "176 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda bros 160",
    leftVolume: "180 ± 2,5 ml",
    rightVolume: "180 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda lead 110",
    leftVolume: "89 ± 1,0 ml",
    rightVolume: "89 ± 1,0 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda adv",
    leftVolume: "127 ± 2,5 ml",
    rightVolume: "127 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda elite 125",
    leftVolume: "85 ± 2,5 ml",
    rightVolume: "85 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda sahara 300",
    leftVolume: "570 ± 2,5 ml",
    rightVolume: "570 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xr 400",
    leftVolume: "570 ml",
    rightVolume: "570 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda tornado 300",
    leftVolume: "570 ± 2,5 ml",
    rightVolume: "570 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda tornado 250",
    leftVolume: "586 ± 2,5 ml",
    rightVolume: "586 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xr 200",
    leftVolume: "312 ml",
    rightVolume: "312 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xlx 350r",
    leftVolume: "418 ml",
    rightVolume: "418 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xlx 250r",
    leftVolume: "300 ml",
    rightVolume: "300 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xlr 125",
    leftVolume: "170 ml",
    rightVolume: "170 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xl 700 transalp",
    leftVolume: "598 ± 2,5 ml",
    rightVolume: "598 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xl 250r",
    leftVolume: "300 ml",
    rightVolume: "300 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda xl 125",
    leftVolume: "155 ml",
    rightVolume: "155 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda x adv",
    leftVolume: "596 ml",
    rightVolume: "586 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda vt 600 shadow",
    leftVolume: "449 ml",
    rightVolume: "449 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda shadow 750",
    leftVolume: "487 ± 2,5 ml",
    rightVolume: "487 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda sh 300i",
    leftVolume: "149 ± 2,5 ml",
    rightVolume: "149 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda sh 150i",
    leftVolume: "100 ± 1,0 ml",
    rightVolume: "100 ± 1,0 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda pcx 160 2023",
    leftVolume: "135 ± 2,5 ml",
    rightVolume: "135 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda nc 750x",
    leftVolume: "435 ± 2,5 ml",
    rightVolume: "435 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda nc 700x",
    leftVolume: "514 ± 2,5 ml",
    rightVolume: "514 ± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
  {
    model: "honda fan 125",
    leftVolume: "74,5 ± 2,5 ml",
    rightVolume: "74,5± 2,5 ml",
    recommendation: "Recomenda-se óleo de suspensão SAE 10W.",
  },
];
